import React from 'react';
import {
    FaBell,
    FaBook,
    FaBullhorn,
    FaCalendarAlt,
    FaChartLine,
    FaCheckCircle,
    FaCog,
    FaComments,
    FaEnvelope,
    FaExclamationCircle,
    FaExclamationTriangle,
    FaFileMedical,
    FaInfoCircle,
    FaLeaf,
    FaLock,
    FaMoon,
    FaNotesMedical,
    FaPencilAlt,
    FaRobot,
    FaSnowflake,
    FaSun,
    FaTint,
    FaTooth,
    FaUser,
    FaVial,
    FaClinicMedical,
    FaRegClock,
    FaBan,
    FaSyncAlt,
    FaCalendarTimes,
} from 'react-icons/fa';

const ICON_MAP = {
    'calendar-outline': FaCalendarAlt,
    'calendar-clear-outline': FaCalendarTimes,
    'notifications-outline': FaBell,
    'alarm-outline': FaRegClock,
    'checkmark-circle-outline': FaCheckCircle,
    'close-circle-outline': FaExclamationCircle,
    'warning-outline': FaExclamationTriangle,
    'alert-circle-outline': FaExclamationCircle,
    'chatbubble-outline': FaComments,
    'megaphone-outline': FaBullhorn,
    'person-outline': FaUser,
    'create-outline': FaPencilAlt,
    'settings-outline': FaCog,
    'sparkles-outline': FaRobot,
    'options-outline': FaInfoCircle,
    'water-outline': FaTint,
    'snow-outline': FaSnowflake,
    'checkmark-done-outline': FaCheckCircle,
    'tooth-outline': FaTooth,
    'toothbrush': FaTooth,
    'nutrition-outline': FaLeaf,
    'cafe-outline': FaNotesMedical,
    'sunny-outline': FaSun,
    'moon-outline': FaMoon,
    'flask-outline': FaVial,
    'document-text-outline': FaFileMedical,
    'help-circle-outline': FaInfoCircle,
    'business-outline': FaClinicMedical,
    'time-outline': FaRegClock,
    'medkit-outline': FaNotesMedical,
    'stats-chart-outline': FaChartLine,
    'mail-outline': FaEnvelope,
    'book-outline': FaBook,
    'lock-closed-outline': FaLock,
    'ban-outline': FaBan,
    'sync-outline': FaSyncAlt,
    bone: FaFileMedical,
};

export default function PatientIcon({ name = '', size = 18, color = 'currentColor', style }) {
    const IconComponent = ICON_MAP[name] || FaInfoCircle;
    return <IconComponent size={size} color={color} style={style} />;
}
