export const mobileTheme = {
  colors: {
    background: '#f4fbff',
    backgroundMuted: '#e9f7ff',
    surface: '#ffffff',
    surfaceAlt: '#f2fbff',
    border: '#cfe9f5',
    borderStrong: '#9fd7ec',
    text: '#12324a',
    textMuted: '#4f6c7e',
    textSoft: '#7b97a8',
    primary: '#01538b',
    primaryDark: '#013b63',
    primarySoft: '#dceffc',
    secondary: '#2dccf6',
    secondaryDark: '#149fc5',
    secondarySoft: '#dff8ff',
    accent: '#2dccf6',
    success: '#2dccf6',
    successSoft: '#dff8ff',
    warning: '#01538b',
    warningSoft: '#dceffc',
    danger: '#01538b',
    dangerSoft: '#dceffc',
    info: '#2dccf6',
    infoSoft: '#dff8ff',
    overlay: 'rgba(1, 83, 139, 0.16)',
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
  },
  radii: {
    sm: 12,
    md: 18,
    lg: 24,
    pill: 999,
  },
  shadows: {
    card: {
      shadowColor: '#01538b',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.08,
      shadowRadius: 20,
      elevation: 4,
    },
    soft: {
      shadowColor: '#01538b',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 2,
    },
  },
};

export const statusPalette = {
  pending: { backgroundColor: '#dff8ff', color: '#149fc5', dot: '#2dccf6' },
  confirmed: { backgroundColor: '#dceffc', color: '#013b63', dot: '#01538b' },
  'in-clinic': { backgroundColor: '#dceffc', color: '#013b63', dot: '#01538b' },
  completed: { backgroundColor: '#dff8ff', color: '#149fc5', dot: '#2dccf6' },
  cancelled: { backgroundColor: '#e9f7ff', color: '#7b97a8', dot: '#7b97a8' },
};
